FROM node:22

ARG PSQL_URL
ARG JWT_SECRET

ENV PSQL_URL=${PSQL_URL}
ENV JWT_SECRET=${JWT_SECRET}

WORKDIR /app

COPY package*.json ./

COPY . .

RUN npm install

RUN npm run build

CMD ["sh", "-c", "npx prisma generate && npm run gitdockerseed && node dist/src/main.js"]