name: build docker image

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "davidlblanco" --password-stdin

      - name: Set Docker image tag and environment variables
        id: vars
        run: |
          echo "IMAGE_TAG=tech-savior:latest" >> $GITHUB_ENV
          echo "PSQL_URL=${{ secrets.PSQL_URL }}" >> $GITHUB_ENV
          # echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build \
            --build-arg PSQL_URL=${{ secrets.PSQL_URL }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -f Dockerfile-git -t davidlblanco/${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to Docker Hub
        run: docker push davidlblanco/${{ env.IMAGE_TAG }}
